runtime: python312
entrypoint: gunicorn -b :$PORT main2:app

env_variables:
  GOOGLE_CLOUD_PROJECT_ID: web-app-medai
  BUCKET_NAME: audioforweb

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
